apiVersion: v1
kind: Pod # What kind of resource is it?
metadata:
  name: multi-container # Name of the pod
  namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
  - name: sidecar
    image: almalinux:8
    command: ["sleep", "200"]