apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    environment: production
    app: nginx
spec:
  containers:
    - name: nginx-labels
      image: nginx:1.14.2
      ports:
        - containerPort: 80