apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    environment: production
    app: nginx
  annotations:
    com.project.author: "Pavan Kumar"
    com.project.name: roboshop
spec:
  containers:
    - name: nginx-anno
      image: nginx
      ports:
        - containerPort: 80
