apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
    - name: config-pod
      image: nginx
      env:
      - name: COURSE
        valueFrom:
          configMapKeyRef:
            name: course-config
            key: COURSE
      - name: TRAINER
        valueFrom:
          configMapKeyRef:
            name: course-config
            key: TRAINER