apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels: # these labels are replica set labels, every k8 resource can have labels.
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels: # these labels should match with pod labels
      app: nginx
      tier: frontend
      environment: dev
  template: # this one is nothing but pod definition.
    metadata:
      labels: # these are the pod labels.
        app: nginx
        tier: frontend
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2