apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: # These are used for selecting and filtering the pod
    environment: dev
    app: frontend
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
        name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  # search for pods that matches the given labels and attach to it
  selector:
    environment: dev
    app: frontend
    project: roboshop
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80 # this port belongs to service
    targetPort: http-web-svc # this port belongs to container